[package]
name = "cargo-zigbuild"
version = "0.3.0"
edition = "2021"
description = "Compile Cargo project with zig as linker"
license = "MIT"
keywords = ["zig", "cargo"]
readme = "README.md"
repository = "https://github.com/messense/cargo-zigbuild"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.1.0", features = ["derive", "wrap_help"] }
dirs = "4.0.0"
fs-err = "2.6.0"
semver = "1.0.5"
target-lexicon = "0.12.3"
